dist: trusty
language: rust
services: docker

sudo: required

env:
  global:
    # TODO Update this to match the name of your project.
    - CRATE_NAME=ref-trust-cli
matrix:
  include:
    - env: TARGET=Hello
script:
  - bash my-release.sh

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Zane Hitchcox"
  - git config --local user.email "zwhitchcox@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: "DJ9HKORRKbTaQ8z/hwrLiF0Hx3ElbJcNZSKpab002h8/fsbk0ICSrZbEIq/8TEEoFM11ndjGw4f7edE2JVctlsbM1qSMEYkjaUngM77NpVP4ltIY2ZU22apgM5UnNArg/cYoJBllAOd5WzSx2UaePkKpkKGBh7b8x81iJCDYsD/Yj7i3/5NA+v2bl+sWhRQ9BOYuZOBXmhkxfpr9SVUbBFFxUWiSIaN8IBZUYQsHV7p08cz0AE/42hFZXdyU2K9pgzc223eyoTbYiwFeBxjV/Q2ts82mCg1hDdvtp1PoNveJfAfSVSlVmhFYPM+EOYzi5KaeKZoRxglowDjMaul446ok5xKEIri4GfMlVgRmCmQ/tVd1E39SrgCq/1MTwWRpswhQRrsUweNnc79CVKpMnkAxJ3RbU0LuMlMbFr3yeKC2XgYaxAxXJF5RcccBnMQTCZnc8c+8VylvFQKcNCDXhU31ieNSJ6taGe6C/NIHhydCVbUPimYRJlbrTuxkL31tqi6ZdwNn4Ll6kVGUX5p1mFI9BZp//nxH3czyH2l/S8YdXQJSP1ajb7wgxdYOzvnfR9qqlIduhqW8XZfcbra7zpVGxt17H8bnNCdUMzJQlUwM19ZoJGcI9Q19y7ZUQ1jiR+9JG8GZcvg1ys8R7ntBN4ktTLOWp+ek7vVpE65S2sE="
  file: my-release.sh
  skip_cleanup: true

branches:
  only:
    - master
notifications:
  email:
    on_success: never